[#4] 신경망 초기 설계 완료
minjune8506/GeneticAvoidance pull request #5
Opened 2022-05-17 15:30 UTC by kpeel5839

- 입력 8
- 히든 레이어 2 Depth
- 출력 8

2022-05-18 07:03 UTC, kpeel5839 commented
댓글 달아주세요!

2022-05-18 08:27 UTC, SOLokill approved these changes
멋져여 👍

2022-05-20 12:27 UTC, minjune8506 requested changes

2022-05-20 12:27 UTC, minjune8506 commented on dodge/network.py
> +    net = self.softmax(net) # 8 개의 방향 중 다중 분류를 위한, Softmax 적용
5개로 주석 수정 부탁해요

2022-05-20 12:27 UTC, minjune8506 commented on genome.py
> +class Genome() :
이파일은 뭐죠?

2022-05-20 12:27 UTC, minjune8506 commented on dodge/game.py
> +            elif self.out_of_range(enemy) : # 유효한 애들만
out_of_range 함수로 한번더 검사해야 하는 이유는 뭘까요

2022-05-20 12:27 UTC, minjune8506 commented on dodge/game.py
> +        x_y_distance = [0, 0] # 아래 조건에 걸리지 않는 경우는 x 혹은 y 가 겹쳐있는 상태를 의미하기에 0으로 설정이 되어야 한다.
이쪽 변수명좀 전체적으로 다시 정하면 좋을듯!
distance = []
e_x e_y
x_d y_d 등등

2022-05-20 12:27 UTC, minjune8506 commented on dodge/game.py
> +                distance = sqrt(pow(x_y_distance[1], 2) + pow(x_y_distance[0], 2))
0 ^2 1^2 순서로...

2022-05-20 12:27 UTC, minjune8506 commented on dodge/game.py
> +                distance = sqrt(pow(x_y_distance[1], 2) + pow(x_y_distance[0], 2))
(희망사항)

2022-05-20 12:27 UTC, minjune8506 commented on dodge/helpers.py
> +VERTICAL_RATIO = 1 / HEIGHT # 세로 비율
이거 어디에서 쓰이나요?

2022-05-20 12:32 UTC, kpeel5839 commented on dodge/game.py
> +                distance = sqrt(pow(x_y_distance[1], 2) + pow(x_y_distance[0], 2))
나는 항상 y 값을 먼저쓰는데에에 알겠슴둥

2022-05-20 12:33 UTC, kpeel5839 commented on dodge/network.py
> +    net = self.softmax(net) # 8 개의 방향 중 다중 분류를 위한, Softmax 적용
네에엥

2022-05-20 12:33 UTC, kpeel5839 commented on genome.py
> +class Genome() :
Network 로 변경하면서 지웠서영

2022-05-20 12:33 UTC, kpeel5839 commented on dodge/game.py
> +        x_y_distance = [0, 0] # 아래 조건에 걸리지 않는 경우는 x 혹은 y 가 겹쳐있는 상태를 의미하기에 0으로 설정이 되어야 한다.
예아 작명센스가 구려서영

2022-05-20 12:34 UTC, kpeel5839 commented on dodge/helpers.py
> +VERTICAL_RATIO = 1 / HEIGHT # 세로 비율
원래 하려던 방식에서 쓰던 변수인데 혹시 몰라서 남겨놨어영

2022-05-20 12:34 UTC, minjune8506 commented on dodge/game.py
> +        x_y_distance = [0, 0] # 아래 조건에 걸리지 않는 경우는 x 혹은 y 가 겹쳐있는 상태를 의미하기에 0으로 설정이 되어야 한다.
인정~

2022-05-20 12:34 UTC, minjune8506 commented on dodge/helpers.py
> +VERTICAL_RATIO = 1 / HEIGHT # 세로 비율
어짜피 다 짠거고 필요없으면 지워도 될거같아요~

2022-05-20 12:37 UTC, kpeel5839 commented on dodge/game.py
> +            elif self.out_of_range(enemy) : # 유효한 애들만
X 혹은 Y 값이 비정상적으로 음수이거나 width 를 넘어가는 경우에 걸러내려구용

2022-05-20 12:44 UTC, kpeel5839 commented on dodge/game.py
> +            elif self.out_of_range(enemy) : # 유효한 애들만
이거 근데 위에 조건문 고치기만 하면 되네용

2022-05-20 12:45 UTC, kpeel5839 commented on dodge/game.py
> +        x_y_distance = [0, 0] # 아래 조건에 걸리지 않는 경우는 x 혹은 y 가 겹쳐있는 상태를 의미하기에 0으로 설정이 되어야 한다.
응아니야!

2022-05-20 12:45 UTC, kpeel5839 commented on dodge/helpers.py
> +VERTICAL_RATIO = 1 / HEIGHT # 세로 비율
앙대여아어ㅓㅇ 바꿀수도있잖아영

2022-05-20 12:52 UTC, minjune8506 commented on dodge/game.py
> +            elif self.out_of_range(enemy) : # 유효한 애들만
위의 조건문을 고치는게 아니라 그냥 else로 쓰면 되는거아닌가?

2022-05-20 12:53 UTC, minjune8506 commented on dodge/game.py
> +            elif self.out_of_range(enemy) : # 유효한 애들만
위치가 이상하면 아예 안움직이고 false로 남아있고 걸러지니까

2022-05-20 12:53 UTC, minjune8506 commented on dodge/helpers.py
> +VERTICAL_RATIO = 1 / HEIGHT # 세로 비율
그때가서 만드세요...ㅎㅎ

2022-05-20 12:54 UTC, minjune8506 commented on genome.py
> +class Genome() :
안지워졌는데요?

2022-05-20 15:06 UTC, kpeel5839 commented on dodge/game.py
> +            elif self.out_of_range(enemy) : # 유효한 애들만
else 로 하게 되면 안움직이는 경우에 값이 -1, 혹은 범위를 넘어간 값이 넘어오게 되지용
위치가 이상하면 아예 안움직이고 false 로 남아있고 걸러지니까 민준이가 말했던 것 처럼
그냥 else 로 받게 되면 이상한 값들도 연산하게 되니까영

2022-05-20 15:07 UTC, kpeel5839 commented on genome.py
> +class Genome() :
<img width="254" alt="image" src="https://user-images.githubusercontent.com/89840550/169557567-64ce9982-805c-416b-abc7-19f72248b3b5.png">

저는 genome 이 없는데 킹상하네요

2022-05-21 03:14 UTC, minjune8506 approved these changes

2022-05-21 03:15 UTC, merged